version: "1.0"

services:
   backend:
      build: ./api
      ports:
         - 3001:3001
      volumes:
         - ./api:/backend
         - /backend/node_modules
      container_name: backend
      restart: always
      depends_on:
         - db

   db:
      image: mysql
      container_name: mysql
      ports:
         - 3306:3306
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      volumes:
         - db_data:/var/lib/mysql
      restart: always

   app:
      build: ./web
      ports:
         - 3000:80
      container_name: app
      restart: always
      depends_on:
         - backend
   
volumes:
 db_data:
